ASPEP_DATA_CONFIG = {
    2000: {"header_start": 1, "header_end": 3},
    2001: {"header_start": 3, "header_end": 5},
    2002: {"header_start": 1, "header_end": 3},
    2003: {"header_start": 1, "header_end": 3},
    2004: {"header_start": 1, "header_end": 3},
    2005: {"header_start": 1, "header_end": 3},
    2006: {"header_start": 1, "header_end": 3},
    2007: {"header_start": 9, "header_end": 11},
    2008: {"header_start": 9, "header_end": 11},
    2009: {"header_start": 10, "header_end": 12},
    2010: {"header_start": 10, "header_end": 12},
    2011: {"header_start": 10, "header_end": 12},
    2012: {"header_start": 11, "header_end": 13},
    2013: {"header_start": 11, "header_end": 13},
    2014: {"header_start": 9, "header_end": 11},
    2015: {"header_start": 9, "header_end": 11},
    2016: {"header_start": 9, "header_end": 11},
    2017: {"header_start": 11, "header_end": 13},
    2018: {"header_start": 12, "header_end": 14},
    2019: {"header_start": 12, "header_end": 14},
    2020: {"header_start": 12, "header_end": 14},
    2021: {"header_start": 12, "header_end": 14},
    2022: {"header_start": 12, "header_end": 14},
    2023: {"header_start": 12, "header_end": 14},
    2024: {"sheet_name": "Data"},  # no header_* keys → tidy headers
}

COLUMN_MAP = {
    "fulltime_and_parttime_employment": "ft_pt_employment", 
    "fulltime_employees": "ft_employment",
    "fulltime_employment": "ft_employment",
    "fulltime_equivalent_employment": "ft_eq_employment",
    "fulltime_pay": "ft_pay",
    "fulltime_payroll": "ft_pay",
    "march_pay": "total_pay",
    "parttime_employees": "pt_employment",
    "parttime_employment": "pt_employment",
    "parttime_hours": "pt_hour",
    "parttime_pay": "pt_pay",
    "parttime_payroll": "pt_pay",
    "total_fulltime_and_parttime_employment": "ft_pt_employment", 
    "total_march_payroll": "total_pay",
    "total_payroll": "total_pay",
}

NEW_COLUMN_MAP_2024 = {
    "Geographic Area Name": "state",
    "Meaning of Aggregate Description": "gov_function",
    "Full-Time Employment": "ft_employment",
    "Full-Time Payroll": "ft_pay",
    "Part-Time Employment": "pt_employment",
    "Part-Time Payroll": "pt_pay",
    "Part-Time Hours": "pt_hours",
    "Full-Time Equivalent Employment": "ft_eq_employment",
    "Total Full-Time and Part-Time Employment": "ft_pt_employment",
    "Total Full-Time and Part-Time Payroll": "total_pay",
}

NUMERIC_COLS_2024 = [
    "ft_employment", "ft_pay", "pt_employment", "pt_pay", "pt_hours",
    "ft_eq_employment", "ft_pt_employment", "total_pay",
]


GOV_FUNCTION_MAP = {
    "total":"total - all government employment functions",
    "financial administration":"financial administration",
    "financial admin":"financial administration",
    "central administration":"other government administration",
    "central admin":"other government administration",
    "judicial & legal":"judicial and legal",
    "judicial-legal":"judicial and legal",
    "police arrest":"police protection - persons with power of arrest",
    "police-arrest":"police protection - persons with power of arrest",
    "persons with power of arrest":"police protection - persons with power of arrest",
    "police with power of arrest":"police protection - persons with power of arrest",
    "police protection - officers":"police protection - persons with power of arrest",
    "police officers only":"police protection - persons with power of arrest",
    "police-other":"police protection - other",
    "police - other":"police protection - other",
    "police other":"police protection - other",
    "other police employees":"police protection - other",
    # "other employees":"police protection - other",
    "correction":"corrections",
    "streets & highways":"highways",
    "streets & hwys":"highways",
    "airports":"air transportation",
    "water transportation":"sea and inland port facilities",
    "water transport and terminals":"sea and inland port facilities",
    "water transport & terminals":"sea and inland port facilities",
    "water transport":"sea and inland port facilities",
    "water transport and canals":"sea and inland port facilities",
    "social insurance admin":"social insurance administration",
    "soc insur admin":"social insurance administration",
    "solid waste mgmt":"solid waste management",
    "sewage disposal":"sewerage",
    "parks & recreation":"parks and recreation",
    "housing & comm dev":"housing and community development",
    "housing & community development":"housing and community development",
    "housing and community developmen":"housing and community development",
    "elem & sec instruction":"education - elementary and secondary instructional",
    "elem & sec instructional employees":"education - elementary and secondary instructional",
    "elem & sec instructional":"education - elementary and secondary instructional",
    "instructional employees":"education - elementary and secondary instructional",
    "elem&sec instruct":"education - elementary and secondary instructional",
    "elem&sec other-tot":"education - elementary and secondary other",
    "elem & sec - other":"education - elementary and secondary other",
    "elem & sec other employees":"education - elementary and secondary other",
    "elem & secondary - other":"education - elementary and secondary other",
    "elem & sec  - other":"education - elementary and secondary other",
    'elem & sec admin/cler':"education - elementary and secondary other",
    'elem & sec oper/maint':"education - elementary and secondary other", 
    'elem & sec cafeteria':"education - elementary and secondary other",
    'elem & sec bus transit':"education - elementary and secondary other", 
    'elem & sec health/rec':"education - elementary and secondary other",
    'elem & sec student':"education - elementary and secondary other", 
    'elem & sec unalloc':"education - elementary and secondary other",
    'higher ed - instructional':"education - higher education instructional", 
    "higher ed instructional employees":"education - higher education instructional", 
    "higher ed instructional":"education - higher education instructional", 
    "higher ed instruct":"education - higher education instructional",
    'higher ed - other':"education - higher education other",
    "higher ed other":"education - higher education other",
    "higher ed - other":"education - higher education other",
    "higher ed other employees":"education - higher education other",
    'other education':"education - other",
    "other ed - state":"education - other",
    "local libraries":"libraries",
    'other & unallocable':"all other and unallocable",
    "other and unallocable":"all other and unallocable",
    "liquor stores":"state liquor stores"
}

STATE_CODE_MAP = {
    "us":"united states",
    "al":"alabama",
    "ak":"alaska",
    "az":"arizona",
    "ar":"arkansas",
    "ca":"california",
    "co":"colorado",
    "ct":"connecticut",
    "de":"delaware",
    "fl":"florida",
    "ga":"georgia",
    "hi":"hawaii",
    "id":"idaho",
    "il":"illinois",
    "in":"indiana",
    "ia":"iowa",
    "ks":"kansas",
    "ky":"kentucky",
    "la":"louisiana",
    "me":"maine",
    "md":"maryland",
    "ma":"massachusetts",
    "mi":"michigan",
    "mn":"minnesota",
    "ms":"mississippi",
    "mo":"missouri",
    "mt":"montana",
    "ne":"nebraska",
    "nv":"nevada",
    "nh":"new hampshire",
    "nj":"new jersey",
    "nm":"new mexico",
    "ny":"new york",
    "nc":"north carolina",
    "nd":"north dakota",
    "oh":"ohio",
    "ok":"oklahoma",
    "or":"oregon",
    "pa":"pennsylvania",
    "ri":"rhode island",
    "sc":"south carolina",
    "sd":"south dakota",
    "tn":"tennessee",
    "tx":"texas",
    "ut":"utah",
    "vt":"vermont",
    "va":"virginia",
    "wa":"washington",
    "wv":"west virginia",
    "wi":"wisconsin",
    "wy":"wyoming"
}

STATE_MAP = {v: k.upper() for k, v in STATE_CODE_MAP.items()}
